//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopServerLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventorySet
    {
        public int InventoryId { get; set; }
        public long Amount { get; set; }
        public int ProductId { get; set; }
        public int CustomerId { get; set; }
    
        public virtual CustomerSet CustomerSet { get; set; }
        public virtual ProductSet ProductSet { get; set; }
    }
}
