//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopServerLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.SqlClient;
    public partial class shopDBEntities1 : DbContext
    {
        public shopDBEntities1()
            : base(@"metadata=res://*/mymodel.csdl|res://*/mymodel.ssdl|res://*/mymodel.msl;provider=System.Data.SqlClient;provider connection string='data source=(localdb)\MSSQLLocalDB;initial catalog=shopDB;integrated security=True;pooling=False;MultipleActiveResultSets=True;App=EntityFramework'") {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder) {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<CustomerSet> CustomerSet { get; set; }
        public virtual DbSet<InventorySet> InventorySet { get; set; }
        public virtual DbSet<ProductSet> ProductSet { get; set; }
    }
}
